[package]
name = "slang"
version = "0.1.0"
authors = ["Agoston Szepessy <agoston.the.dev@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lalrpop = "0.19.3"
logos = "0.11.4"
thiserror = "1.0.23"
