[package]
name = "slang"
version = "0.1.0"
authors = ["Agoston Szepessy <agoston.the.dev@gmail.com>"]
edition = "2018"

[lib]
name = "libslang"
path = "src/libslang/lib.rs"

[dependencies]
lalrpop = "0.19.3"
logos = "0.11.4"
thiserror = "1.0.23"
